# Generated by Django 2.0.2 on 2018-02-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiddlewareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.TextField()),
                ('dt_request', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
