# Generated by Django 2.0.2 on 2018-02-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBLoggerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('bio', models.CharField(choices=[(1, 'update'), (2, 'create'), (3, 'delete')], max_length=10)),
            ],
        ),
    ]
