# Generated by Django 2.0.2 on 2018-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_logger', '0002_auto_20180209_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbloggermodel',
            name='model',
            field=models.IntegerField(),
        ),
    ]
