# Generated by Django 2.0.2 on 2018-02-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_logger', '0003_auto_20180209_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbloggermodel',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
